### ISSUE TITLE
include information on how to contact the WG

### ISSUE THREAD

**Issue by garu** [CPAN-Security/security.metacpan.org#3]
Could be a form or a list of many ways to reach out (gh issue, irc, email, social networks, etc)

**Comment by sjn** [comment]
I've started a little on this on the website.

Also @stigtsp and I had a chat today, and I suggested that we think about this in *three* stages:

1. A private mailing list (I guess this is the cpan-security at perl.org list?), where sensitive issues are discussed. This list needs to be limited access, and new members should be vetted (process documented in #20, I guess?)
2. A main public forum, where non-sensitive issues are discussed. Right now  we have the IRC channel, but we should probably look into something better? We have several options here, but need probably to give this a proper think. Sensitive issues are redirected to the private mailing list from here. Anyone can join the forum.
3. A series of funneling channels, that direct users from other networks or social media to the main public forum. For example, establish a #cpan-security channel on different IRC servers, on Matrix, on the Fediverse (e.g. @cpan_security@perl.social), and on relevant slack and discord servers. Anyone can read these channels, but they should probably just send people to the correct place, and not have any important discussions.

What do you think?

**Comment by timlegge** [comment]
Sounds prudent.  I just kind of showed up myself.  I agree a private list is needed for sensitive issues with more vetting.  Some of it would end up being "oh I know person A they are great to deal with and known in the Perl community" but there is a bit of a risk there of continuing to rely on already overloaded people.  Likely look for an interest in security, some sort of security background would definitely help.  Often reporters run into issues because a developer/maintainer does not initially understand the repercussion of a particular flaw.

**Comment by sjn** [comment]
Direct traffic to https://security.metacpan.org from...

- [ ] TPRF Slack #cpan-security
- [ ] Mastodon @cpan-security@perl.social
- [ ] https://security.cpan.org
- …
